ALTER TABLE cargo
    DROP CONSTRAINT FK_CARGO_ON_CARGO;



ALTER TABLE cargo
    DROP COLUMN cargo_id;


ALTER TABLE cargo
    ADD unit_id BIGINT;
ALTER TABLE cargo
    ADD CONSTRAINT FK_CARGO_ON_CARGO FOREIGN KEY (unit_id) REFERENCES unit (id);
